# See configuration examples by looking at the release.json and .manifest.json in the
# https://github.com/NEIAAC/typescript-template and https://github.com/NEIAAC/python-template repositories
# For actions like forcing a specific release version or working with multiple release
# branches, see the official documentation: https://github.com/googleapis/release-please
name: release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.metadata.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@3612a99d75bd7a010bb03d6e2ee3e2392b7392fb # v4.2.0
        id: metadata
        with:
          config-file: release.json
          manifest-file: .manifest.json
